apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: gotham-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotham-web
  template:
    metadata:
      labels:
        app: gotham-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
