apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gotham-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nick-draper/app-set.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: gotham-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
